### ISSUE TITLE
Add timeout to `init_process_group` in `entrypoint`

### ISSUE THREAD

**Issue by apoorvkh** [apoorvkh/torchrunx#43]
Question: what's the longest a distributed operation should reasonably take?
How long would it take to "all-gather" a large amount of memory (like 80 GB)?

Let's set a smaller default timeout... maybe 180 seconds?
And then we can pass an argument to override this.

https://github.com/apoorvkh/torchrunx/blob/cd1a8955aa7123ee68860a5f50fa18fa9edfac6b/src/torchrunx/agent.py#L83-L85

**Comment by apoorvkh** [comment]
https://github.com/pytorch/pytorch/pull/13056#issuecomment-432751779

**Comment by apoorvkh** [comment]
I guess they added `monitored_barrier` but it only works for GLOO.

https://pytorch.org/docs/stable/distributed.html#torch.distributed.monitored_barrier

I still think we can reduce this default, but allow users to override if desired.

**Comment by pmcurtin** [comment]
> https://github.com/pytorch/pytorch/pull/13056#issuecomment-432751779

Oh yeah, that'd be great. I was thinking barriers might be an issue. I think this is a PyTorch issue really. 

> I still think we can reduce this default, but allow users to override if desired.

Yeah that sounds reasonable.
