### ISSUE TITLE
Add both `func_args` and `func_kwargs` to `launch`

### ISSUE THREAD

**Issue by apoorvkh** [apoorvkh/torchrunx#46]

**Comment by apoorvkh** [comment]
or maybe just `*args` and `**kwargs`?

**Comment by pmcurtin** [comment]
Yeah this seems like a good idea. Once I finish logging I'll quickly add it.

**Comment by apoorvkh** [comment]
I made a new branch last night with this change (but didn't test it). Feel free to adjust that!
