### ISSUE TITLE
Option to disable init_process_group entirely?

### ISSUE THREAD

**Issue by apoorvkh** [apoorvkh/torchrunx#48]
Especially with ssh launching, logging and return values, it seems like we are building a generally useful "multiprocessing/launching" library, beyond just torch specifically. Should we support a setting where a user might want to launch a function, but not create a PyTorch process group (i.e. the one in entrypoint, not LauncherAgentGroup)?

More generally, I still like the PyTorch focus and branding of this library: because PyTorch training is probably a very common use case and also because I think we are inherently tied to the PyTorch dependency (for distributed functions and GLOO, in LauncherAgentGroup). I don't think there is an alternative to GLOO that is as easy to use and install. There is MPI but I think it is notoriously system-specific.

**Comment by apoorvkh** [comment]
Or we can just leave the `init_process_group` statement and end-users can ignore it it they won't use it. I don't think there is a performance impact or anything.

**Comment by pmcurtin** [comment]
Yeah, it's probably fine to leave it. It's an easy fix if it's ever requested... 

One day if we switch to sockets instead of `torch.distributed` for our launcher-agent communication, maybe we can make it optional.
