### ISSUE TITLE
`Launcher` as a contextmanager

### ISSUE THREAD

**Issue by apoorvkh** [apoorvkh/torchrunx#50]
Right now, we ask the user to supply

```python
Launcher(...).run(func, func_args=(), func_kwargs={})
```

But this does not support static type checking. So the type checker (e.g. mypy or pyright) won't check if the arguments or keywords are actually compatible with `func`. Perhaps we can add support for `Launcher` like:

```python
with Launcher(...):
    func(arg1, arg2, ...)

    another_func(arg1, arg2, ...)
```

This would intercept each call (e.g. `func()` and `another_func()`) within the `with` block and launch them one at a time. In this example, this would block until `func` is complete.

I've thought about how to do things like this before, but need to search and think again. Will tag thoughts onto here.

**Comment by pmcurtin** [comment]
That's quite interesting, and I think it'd be worthwhile too. Related, we need to add a call to `dist.destroy_process_group()` in `Launcher.run` or else repeated calls to it won't work (i found this while testing). 

I think I can already imagine how we'd do this, we can talk about it tomorrow.

**Comment by apoorvkh** [comment]
Unfortunately, this is probably non-trivial to implement cleanly and out of scope. Closing for now.
